### ISSUE TITLE
Very useful code, request to complete TODO, Thank you very much.

### ISSUE THREAD

**Issue by huiyang-work** [jamiegyoung/microsoft-sticky-notes-py#1]
TODO:
***Add editing of sticky notes
**Implement searching for sticky notes other than exact text
**Finish implementing match exact text
Add usage of markdown within the sticky notes
Add custom creation date

**Comment by jamiegyoung** [comment]
Sorry I missed this! The project hasn't been worked on in a while but I may get back to it if it is of any use
